services:
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://vault_user:vault_password@db:5432/vault_db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: vault_user
      POSTGRES_PASSWORD: vault_password
      POSTGRES_DB: vault_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    # We removed the ports mapping here!

volumes:
  pgdata: